Fix/update abis and refactor bridge abi management
rsksmart/rsk-contract-parser pull request #34
Opened 2023-07-27 19:16 UTC by IOVgomezdn

2023-08-09 20:00 UTC, sergio-jara approved these changes
I choose to believe

2023-08-17 18:23 UTC, ilanolkies requested changes
👌🏻 good testing

2023-08-17 18:23 UTC, ilanolkies commented on src/lib/nativeContracts/bridgeAbi.js
> +  } else {
I would remove else after return

See https://eslint.org/docs/latest/rules/no-else-return#rule-details

2023-08-17 18:27 UTC, IOVgomezdn commented on src/lib/nativeContracts/bridgeAbi.js
> +  } else {
done

2023-08-17 18:30 UTC, ilanolkies approved these changes

2023-08-17 19:22 UTC, merged